# remote_theme: ivnsam/minima
theme: jekyll-theme-minima
minima:
  skin: dark
title: ivnsam's pages
author:
  name: ivnsam
  email: iwansam1996@gmail.com
github_username: ivnsam
# site_favicon: favicon.png